### ISSUE TITLE
Sidebar issue on new version. 

### ISSUE THREAD

**Issue by chemamora** [wolffe/the-greyhound#1]
Hi there, 

Thanks for theme, I really like it, really simple, minimal and relaxed environment to work on brackets.

I have noticed that the new version of the theme has change the sidebar behaviour. When readjusting the width of the sidebar the editor-holder is not linked to the sidebar anymore. 

Any chance of fixing this? 

![screenshot at jan 31 10-33-43](https://cloud.githubusercontent.com/assets/14870135/22461348/cc80f7ea-e7a0-11e6-8c9f-698301b827cf.png)

**Comment by wolffe** [comment]
Hi, thanks. I know about this, I have it fixed and I will update it this afternoon.

**Comment by chemamora** [comment]
Great thanks

**Comment by wolffe** [comment]
Fixed in The Greyhound Companion `0.0.5`.
